version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Setup Virtual Environment and Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Unit Tests with Pytest
          command: |
            . venv/bin/activate
            export PYTHONPATH=.
            pytest

workflows:
  version: 2
  test-workflow:
    jobs:
      - build-and-test
