version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install Pip via System Package Manager
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip python3-dev
      - run:
          name: Install Project Dependencies
          command: |
            pip3 install -r requirements.txt
      - run:
          name: Run Unit Tests with Pytest
          command: |
            export PYTHONPATH=.
            python3 -m pytest

workflows:
  version: 2
  test-workflow:
    jobs:
      - build-and-test
